default_language_version:
  python: python3.14

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --force-exclude
        language: system
        types: [python]
        files: ^backend/src/
        stages: [pre-push]

      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        files: ^backend/src/
        stages: [pre-push]

      - id: pytest
        name: pytest
        entry: pytest backend/tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: lint
        name: lint
        entry: npm run lint
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
