class DomainError(Exception):
    """Base for all domain-level errors."""


class NotFoundError(DomainError): ...


class ForbiddenError(DomainError): ...


class ConflictError(DomainError): ...


class RateLimitedError(DomainError): ...


class BoardNotFoundError(NotFoundError): ...


class ThreadNotFoundError(NotFoundError): ...


class PostNotFoundError(NotFoundError): ...


class ThreadLockedError(ForbiddenError): ...


class BumpLimitReachedError(ForbiddenError): ...


class PostAlreadyEditedError(ConflictError): ...


class EditWindowExpiredError(ForbiddenError): ...


class NotPostAuthorError(ForbiddenError): ...


class IpBannedError(ForbiddenError): ...
