class DomainError(Exception):
    """Base for all domain-level errors."""


class NotFoundError(DomainError): ...


class ForbiddenError(DomainError): ...


class ConflictError(DomainError): ...


class RateLimitedError(DomainError): ...


class BadRequestError(DomainError): ...


class UnauthorizedError(DomainError): ...


class BoardNotFoundError(NotFoundError): ...


class ThreadNotFoundError(NotFoundError): ...


class PostNotFoundError(NotFoundError): ...


class ThreadLockedError(ForbiddenError): ...


class BumpLimitReachedError(ForbiddenError): ...


class PostAlreadyEditedError(ConflictError): ...


class EditWindowExpiredError(ForbiddenError): ...


class NotPostAuthorError(ForbiddenError): ...


class IpBannedError(ForbiddenError): ...


class BoardAlreadyExistsError(ConflictError): ...


class UnsupportedMediaTypeError(BadRequestError): ...


class FileTooLargeError(BadRequestError): ...


class InvalidCaptchaError(BadRequestError): ...


class InvalidCredentialsError(UnauthorizedError): ...


class ModInactiveError(UnauthorizedError): ...
