apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: yachan
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: yachan-backend:dev
          imagePullPolicy: IfNotPresent
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: yachan-secret
