/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Boards */
        get: operations["list_boards_api_boards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Board */
        get: operations["get_board_api_boards__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Latest Threads */
        get: operations["list_latest_threads_api_threads_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{board_slug}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Threads */
        get: operations["list_threads_api__board_slug__threads_get"];
        put?: never;
        /** Create Thread */
        post: operations["create_thread_api__board_slug__threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{board_slug}/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["get_thread_api__board_slug__threads__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{board_slug}/threads/{thread_id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Reply */
        post: operations["create_reply_api__board_slug__threads__thread_id__posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{board_slug}/posts/{post_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Post */
        patch: operations["edit_post_api__board_slug__posts__post_number__patch"];
        trace?: never;
    };
    "/api/{board_slug}/posts/{post_number}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post History */
        get: operations["get_post_history_api__board_slug__posts__post_number__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{board_slug}/posts/{post_number}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Report */
        post: operations["create_report_api__board_slug__posts__post_number__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/captcha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issue Captcha */
        get: operations["issue_captcha_api_captcha_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site Stats */
        get: operations["get_site_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mod/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_mod_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mod/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Board */
        post: operations["create_board_api_mod_boards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mod/boards/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Boards */
        put: operations["reorder_boards_api_mod_boards_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mod/boards/{board_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Board */
        patch: operations["update_board_api_mod_boards__board_slug__patch"];
        trace?: never;
    };
    "/api/mod/{board_slug}/posts/{post_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Post */
        delete: operations["delete_post_api_mod__board_slug__posts__post_number__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mod/{board_slug}/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Thread */
        delete: operations["delete_thread_api_mod__board_slug__threads__thread_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mod/{board_slug}/threads/{thread_id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock Thread */
        post: operations["lock_thread_api_mod__board_slug__threads__thread_id__lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mod/{board_slug}/threads/{thread_id}/sticky": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sticky Thread */
        post: operations["sticky_thread_api_mod__board_slug__threads__thread_id__sticky_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mod/{board_slug}/posts/{post_number}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ban Poster */
        post: operations["ban_poster_api_mod__board_slug__posts__post_number__ban_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mod/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_api_mod_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mod/reports/{report_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Report */
        post: operations["resolve_report_api_mod_reports__report_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttachmentResponse */
        AttachmentResponse: {
            /** Id */
            id: number;
            media_type: components["schemas"]["MediaType"];
            /** Original Name */
            original_name: string;
            /** Url */
            url?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Mime Type */
            mime_type: string;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Size Bytes */
            size_bytes?: number | null;
            moderation_status: components["schemas"]["ModerationStatus"];
        };
        /** BanCreate */
        BanCreate: {
            /** Reason */
            reason?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Board Id */
            board_id?: number | null;
        };
        /** BanResponse */
        BanResponse: {
            /** Id */
            id: number;
            /** Ip Hash */
            ip_hash: string;
            /** Board Id */
            board_id: number | null;
            /** Reason */
            reason: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BoardCreate */
        BoardCreate: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Bump Limit
             * @default 300
             */
            bump_limit: number;
            /**
             * Is Nsfw
             * @default false
             */
            is_nsfw: boolean;
        };
        /** BoardReorder */
        BoardReorder: {
            /** Slugs */
            slugs: string[];
        };
        /** BoardResponse */
        BoardResponse: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Bump Limit */
            bump_limit: number;
            /** Is Active */
            is_active: boolean;
            /** Is Nsfw */
            is_nsfw: boolean;
            /** Position */
            position: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BoardStatsResponse */
        BoardStatsResponse: {
            /** Slug */
            slug: string;
            /** Thread Count */
            thread_count: number;
            /** Post Count */
            post_count: number;
            /** Online Count */
            online_count: number;
        };
        /** BoardUpdate */
        BoardUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Bump Limit */
            bump_limit?: number | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Nsfw */
            is_nsfw?: boolean | null;
        };
        /** Body_create_reply_api__board_slug__threads__thread_id__posts_post */
        Body_create_reply_api__board_slug__threads__thread_id__posts_post: {
            /**
             * Files
             * @default []
             */
            files: string[];
            /** Name */
            name?: string | null;
            /** Body */
            body?: string | null;
            /**
             * Sage
             * @default false
             */
            sage: boolean;
        };
        /** Body_create_thread_api__board_slug__threads_post */
        Body_create_thread_api__board_slug__threads_post: {
            /**
             * Files
             * @default []
             */
            files: string[];
            /** Title */
            title?: string | null;
            /** Name */
            name?: string | null;
            /** Body */
            body?: string | null;
            /**
             * Sage
             * @default false
             */
            sage: boolean;
        };
        /** CaptchaChallengeResponse */
        CaptchaChallengeResponse: {
            /** Token */
            token: string;
            /** Image Base64 Light */
            image_base64_light: string;
            /** Image Base64 Dark */
            image_base64_dark: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImagePreview */
        ImagePreview: {
            /** Url */
            url: string;
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
        };
        /** LatestThreadResponse */
        LatestThreadResponse: {
            /** Id */
            id: number;
            /** Board Slug */
            board_slug: string;
            /** Title */
            title: string | null;
            /** Reply Count */
            reply_count: number;
            /**
             * Bump At
             * Format: date-time
             */
            bump_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            last_reply?: components["schemas"]["ReplyPreview"] | null;
        };
        /**
         * MediaType
         * @enum {string}
         */
        MediaType: "image" | "video" | "gif";
        /** ModLogin */
        ModLogin: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * ModRole
         * @enum {string}
         */
        ModRole: "admin" | "moderator";
        /**
         * ModerationStatus
         * @enum {string}
         */
        ModerationStatus: "pending" | "safe" | "flagged" | "blocked";
        /** OpPostPreview */
        OpPostPreview: {
            /** Body */
            body: string | null;
            /** Body Html */
            body_html: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Images */
            images?: components["schemas"]["ImagePreview"][];
        };
        /** PostEditCreate */
        PostEditCreate: {
            /** New Body */
            new_body?: string | null;
        };
        /** PostEditResponse */
        PostEditResponse: {
            /** Post Id */
            post_id: number;
            /** Original Body */
            original_body: string | null;
            /** Original Body Html */
            original_body_html: string | null;
            /**
             * Edited At
             * Format: date-time
             */
            edited_at: string;
        };
        /** PostResponse */
        PostResponse: {
            /** Id */
            id: number;
            /** Post Number */
            post_number: number;
            /** Thread Id */
            thread_id: number;
            /** Board Id */
            board_id: number;
            /** Name */
            name: string;
            /** Tripcode */
            tripcode: string | null;
            /** Body */
            body: string | null;
            /** Body Html */
            body_html: string | null;
            /** Sage */
            sage: boolean;
            /** Is Op */
            is_op: boolean;
            /** Is Edited */
            is_edited: boolean;
            /** Edited At */
            edited_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Can Edit
             * @default false
             */
            can_edit: boolean;
            /** Attachments */
            attachments?: components["schemas"]["AttachmentResponse"][];
        };
        /** ReplyPreview */
        ReplyPreview: {
            /** Id */
            id: number;
            /** Post Number */
            post_number: number;
            /** Name */
            name: string | null;
            /** Body */
            body: string | null;
            /** Body Html */
            body_html: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReportCreate */
        ReportCreate: {
            /** Reason */
            reason?: string | null;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Id */
            id: number;
            /** Post Id */
            post_id: number;
            /** Board Id */
            board_id: number | null;
            /** Reason */
            reason: string | null;
            /** Is Auto */
            is_auto: boolean;
            /** Is Resolved */
            is_resolved: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SearchResultResponse */
        SearchResultResponse: {
            /** Board Slug */
            board_slug: string;
            /** Thread Id */
            thread_id: number;
            /** Post Number */
            post_number: number;
            /** Is Op */
            is_op: boolean;
            /** Name */
            name: string;
            /** Body */
            body: string | null;
            /** Body Html */
            body_html: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Score */
            score: number;
        };
        /** SiteStatsResponse */
        SiteStatsResponse: {
            /** Board Count */
            board_count: number;
            /** Thread Count */
            thread_count: number;
            /** Post Count */
            post_count: number;
            /** Online Count */
            online_count: number;
            /** Boards */
            boards: components["schemas"]["BoardStatsResponse"][];
        };
        /** ThreadDetailResponse */
        ThreadDetailResponse: {
            /** Id */
            id: number;
            /** Board Id */
            board_id: number;
            /** Title */
            title: string | null;
            /** Is Locked */
            is_locked: boolean;
            /** Is Sticky */
            is_sticky: boolean;
            /** Reply Count */
            reply_count: number;
            /**
             * Bump At
             * Format: date-time
             */
            bump_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            op_post?: components["schemas"]["OpPostPreview"] | null;
            /** Last Replies */
            last_replies?: components["schemas"]["ReplyPreview"][];
            /** Summary */
            summary?: string | null;
            /** Summary Updated At */
            summary_updated_at?: string | null;
            /** Posts */
            posts?: components["schemas"]["PostResponse"][];
        };
        /** ThreadResponse */
        ThreadResponse: {
            /** Id */
            id: number;
            /** Board Id */
            board_id: number;
            /** Title */
            title: string | null;
            /** Is Locked */
            is_locked: boolean;
            /** Is Sticky */
            is_sticky: boolean;
            /** Reply Count */
            reply_count: number;
            /**
             * Bump At
             * Format: date-time
             */
            bump_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            op_post?: components["schemas"]["OpPostPreview"] | null;
            /** Last Replies */
            last_replies?: components["schemas"]["ReplyPreview"][];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            role: components["schemas"]["ModRole"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_boards_api_boards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"][];
                };
            };
        };
    };
    get_board_api_boards__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                board?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_latest_threads_api_threads_latest_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestThreadResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_threads_api__board_slug__threads_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                board_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_thread_api__board_slug__threads_post: {
        parameters: {
            query?: never;
            header: {
                "X-Captcha-Token": string;
                "X-Captcha-Answer": string;
            };
            path: {
                board_slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_thread_api__board_slug__threads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_api__board_slug__threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_slug: string;
                thread_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reply_api__board_slug__threads__thread_id__posts_post: {
        parameters: {
            query?: never;
            header: {
                "X-Captcha-Token": string;
                "X-Captcha-Answer": string;
            };
            path: {
                board_slug: string;
                thread_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_reply_api__board_slug__threads__thread_id__posts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_post_api__board_slug__posts__post_number__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_slug: string;
                post_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostEditCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_history_api__board_slug__posts__post_number__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_slug: string;
                post_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostEditResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api__board_slug__posts__post_number__report_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_slug: string;
                post_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_captcha_api_captcha_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptchaChallengeResponse"];
                };
            };
        };
    };
    get_site_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteStatsResponse"];
                };
            };
        };
    };
    login_api_mod_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_board_api_mod_boards_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_boards_api_mod_boards_order_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardReorder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_board_api_mod_boards__board_slug__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                board_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_api_mod__board_slug__posts__post_number__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                board_slug: string;
                post_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_thread_api_mod__board_slug__threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                board_slug: string;
                thread_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_thread_api_mod__board_slug__threads__thread_id__lock_post: {
        parameters: {
            query?: {
                locked?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                board_slug: string;
                thread_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sticky_thread_api_mod__board_slug__threads__thread_id__sticky_post: {
        parameters: {
            query?: {
                sticky?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                board_slug: string;
                thread_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ban_poster_api_mod__board_slug__posts__post_number__ban_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                board_slug: string;
                post_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_mod_reports_get: {
        parameters: {
            query?: {
                board_id?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_report_api_mod_reports__report_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
