"""add audit_log table and triggers

Revision ID: 0c9f967591bb
Revises: 1a250bdaf2b0
Create Date: 2026-06-04 18:39:36.220972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c9f967591bb'
down_revision: Union[str, Sequence[str], None] = '1a250bdaf2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('op', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('row_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('txid', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_table_name'), 'audit_log', ['table_name'], unique=False)
    # ### end Alembic commands ###

    # generic trigger function: writes every insert/update/delete into audit_log.
    # one statement (dollar-quoted body) so asyncpg accepts it.
    op.execute(
        """
        CREATE FUNCTION audit_log_changes() RETURNS trigger AS $$
        BEGIN
            INSERT INTO audit_log (table_name, op, row_data, old_data, txid, at)
            VALUES (
                TG_TABLE_NAME,
                TG_OP,
                to_jsonb(CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END),
                CASE WHEN TG_OP = 'UPDATE' THEN to_jsonb(OLD) END,
                txid_current(),
                now() AT TIME ZONE 'utc'
            );
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # attach the trigger to each audited table, explicitly per table. audit_log
    # itself is excluded so writing an audit row does not recurse.
    op.execute("CREATE TRIGGER audit_attachment AFTER INSERT OR UPDATE OR DELETE ON attachment FOR EACH ROW EXECUTE FUNCTION audit_log_changes()")
    op.execute("CREATE TRIGGER audit_ban AFTER INSERT OR UPDATE OR DELETE ON ban FOR EACH ROW EXECUTE FUNCTION audit_log_changes()")
    op.execute("CREATE TRIGGER audit_board AFTER INSERT OR UPDATE OR DELETE ON board FOR EACH ROW EXECUTE FUNCTION audit_log_changes()")
    op.execute("CREATE TRIGGER audit_mod_account AFTER INSERT OR UPDATE OR DELETE ON mod_account FOR EACH ROW EXECUTE FUNCTION audit_log_changes()")
    op.execute("CREATE TRIGGER audit_post AFTER INSERT OR UPDATE OR DELETE ON post FOR EACH ROW EXECUTE FUNCTION audit_log_changes()")
    op.execute("CREATE TRIGGER audit_post_backlink AFTER INSERT OR UPDATE OR DELETE ON post_backlink FOR EACH ROW EXECUTE FUNCTION audit_log_changes()")
    op.execute("CREATE TRIGGER audit_post_edit AFTER INSERT OR UPDATE OR DELETE ON post_edit FOR EACH ROW EXECUTE FUNCTION audit_log_changes()")
    op.execute("CREATE TRIGGER audit_report AFTER INSERT OR UPDATE OR DELETE ON report FOR EACH ROW EXECUTE FUNCTION audit_log_changes()")
    op.execute("CREATE TRIGGER audit_thread AFTER INSERT OR UPDATE OR DELETE ON thread FOR EACH ROW EXECUTE FUNCTION audit_log_changes()")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_attachment ON attachment")
    op.execute("DROP TRIGGER IF EXISTS audit_ban ON ban")
    op.execute("DROP TRIGGER IF EXISTS audit_board ON board")
    op.execute("DROP TRIGGER IF EXISTS audit_mod_account ON mod_account")
    op.execute("DROP TRIGGER IF EXISTS audit_post ON post")
    op.execute("DROP TRIGGER IF EXISTS audit_post_backlink ON post_backlink")
    op.execute("DROP TRIGGER IF EXISTS audit_post_edit ON post_edit")
    op.execute("DROP TRIGGER IF EXISTS audit_report ON report")
    op.execute("DROP TRIGGER IF EXISTS audit_thread ON thread")
    op.execute("DROP FUNCTION IF EXISTS audit_log_changes()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_table_name'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
