"""add updated_at via timestamp mixin

Revision ID: 1a250bdaf2b0
Revises: 6c373fe34a6f
Create Date: 2026-06-03 08:38:46.691029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1a250bdaf2b0'
down_revision: Union[str, Sequence[str], None] = '6c373fe34a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # adjusted: each NOT NULL column is added to a populated table as nullable,
    # backfilled from the row's existing timestamp, then set NOT NULL. one
    # explicit block per table (no loop, no server_default).
    op.add_column('attachment', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE attachment SET updated_at = created_at")
    op.alter_column('attachment', 'updated_at', nullable=False)

    op.add_column('ban', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE ban SET updated_at = created_at")
    op.alter_column('ban', 'updated_at', nullable=False)

    op.add_column('board', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE board SET updated_at = created_at")
    op.alter_column('board', 'updated_at', nullable=False)

    op.add_column('mod_account', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE mod_account SET updated_at = created_at")
    op.alter_column('mod_account', 'updated_at', nullable=False)

    op.add_column('post', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE post SET updated_at = created_at")
    op.alter_column('post', 'updated_at', nullable=False)

    op.add_column('post_backlink', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE post_backlink SET updated_at = created_at")
    op.alter_column('post_backlink', 'updated_at', nullable=False)

    op.add_column('report', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE report SET updated_at = created_at")
    op.alter_column('report', 'updated_at', nullable=False)

    op.add_column('thread', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE thread SET updated_at = created_at")
    op.alter_column('thread', 'updated_at', nullable=False)

    # post_edit had no created_at; seed both audit columns from its edited_at
    op.add_column('post_edit', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE post_edit SET created_at = edited_at")
    op.alter_column('post_edit', 'created_at', nullable=False)

    op.add_column('post_edit', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE post_edit SET updated_at = edited_at")
    op.alter_column('post_edit', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'updated_at')
    op.drop_column('report', 'updated_at')
    op.drop_column('post_edit', 'updated_at')
    op.drop_column('post_edit', 'created_at')
    op.drop_column('post_backlink', 'updated_at')
    op.drop_column('post', 'updated_at')
    op.drop_column('mod_account', 'updated_at')
    op.drop_column('board', 'updated_at')
    op.drop_column('ban', 'updated_at')
    op.drop_column('attachment', 'updated_at')
    # ### end Alembic commands ###
