"""add board is_nsfw flag

Revision ID: a62e92ad23db
Revises: 2d7161cf35bc
Create Date: 2026-07-02 13:06:49.157735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a62e92ad23db'
down_revision: Union[str, Sequence[str], None] = '2d7161cf35bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default false backfills existing boards (all non-nsfw), then dropped;
    # the app assigns is_nsfw explicitly (model default false)
    op.add_column('board', sa.Column('is_nsfw', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('board', 'is_nsfw', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'is_nsfw')
    # ### end Alembic commands ###
