"""initial schema

Revision ID: 3724a32996b8
Revises: 
Create Date: 2026-05-29 00:20:33.287563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3724a32996b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('bump_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_slug'), 'board', ['slug'], unique=True)
    op.create_table('mod_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MODERATOR', name='modrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mod_account_username'), 'mod_account', ['username'], unique=True)
    op.create_table('ban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['mod_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ban_ip_hash'), 'ban', ['ip_hash'], unique=False)
    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_sticky', sa.Boolean(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('bump_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_board_id'), 'thread', ['board_id'], unique=False)
    op.create_index(op.f('ix_thread_bump_at'), 'thread', ['bump_at'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_number', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tripcode', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('body_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sage', sa.Boolean(), nullable=False),
    sa.Column('is_op', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('ip_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['mod_account.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'post_number', name='uq_post_board_number')
    )
    op.create_index(op.f('ix_post_board_id'), 'post', ['board_id'], unique=False)
    op.create_index(op.f('ix_post_thread_id'), 'post', ['thread_id'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'GIF', name='mediatype'), nullable=False),
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('md5', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_md5'), 'attachment', ['md5'], unique=False)
    op.create_index(op.f('ix_attachment_post_id'), 'attachment', ['post_id'], unique=False)
    op.create_table('post_backlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_post_id', sa.Integer(), nullable=False),
    sa.Column('target_post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['target_post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_post_id', 'target_post_id', name='uq_backlink_pair')
    )
    op.create_index(op.f('ix_post_backlink_source_post_id'), 'post_backlink', ['source_post_id'], unique=False)
    op.create_index(op.f('ix_post_backlink_target_post_id'), 'post_backlink', ['target_post_id'], unique=False)
    op.create_table('post_edit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('original_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('original_body_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_edit_post_id'), 'post_edit', ['post_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('ip_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['mod_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_post_id'), 'report', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_post_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_post_edit_post_id'), table_name='post_edit')
    op.drop_table('post_edit')
    op.drop_index(op.f('ix_post_backlink_target_post_id'), table_name='post_backlink')
    op.drop_index(op.f('ix_post_backlink_source_post_id'), table_name='post_backlink')
    op.drop_table('post_backlink')
    op.drop_index(op.f('ix_attachment_post_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_md5'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_post_thread_id'), table_name='post')
    op.drop_index(op.f('ix_post_board_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_thread_bump_at'), table_name='thread')
    op.drop_index(op.f('ix_thread_board_id'), table_name='thread')
    op.drop_table('thread')
    op.drop_index(op.f('ix_ban_ip_hash'), table_name='ban')
    op.drop_table('ban')
    op.drop_index(op.f('ix_mod_account_username'), table_name='mod_account')
    op.drop_table('mod_account')
    op.drop_index(op.f('ix_board_slug'), table_name='board')
    op.drop_table('board')
    # ### end Alembic commands ###
    # autogenerate creates these enum types implicitly but never drops them
    sa.Enum(name='mediatype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='modrole').drop(op.get_bind(), checkfirst=True)
