"""add board position

Revision ID: 6c373fe34a6f
Revises: 3724a32996b8
Create Date: 2026-06-02 18:08:13.452910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c373fe34a6f'
down_revision: Union[str, Sequence[str], None] = '3724a32996b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default '0' lets the NOT NULL column be added to an existing table
    op.add_column('board', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_board_position'), 'board', ['position'], unique=False)
    # seed a stable initial order for existing rows (alphabetical by slug)
    op.execute(
        """
        UPDATE board
        SET position = ranked.rn
        FROM (
            SELECT id, (row_number() OVER (ORDER BY slug) - 1) AS rn
            FROM board
        ) AS ranked
        WHERE board.id = ranked.id
        """
    )
    # drop the server default; the app assigns position explicitly (model default 0)
    op.alter_column('board', 'position', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_position'), table_name='board')
    op.drop_column('board', 'position')
    # ### end Alembic commands ###
